version: "3"
services:
  face_recognition:
    image: shinoi2/pji-research:face_recognition
    container_name: face_recognition
    volumes:
      - "/home/face_recognition/data:/data"
  http_api_service:
    image: shinoi2/pji-research:http_api_service
    environment:
      - GRPC_POLL_STRATEGY=poll
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    extra_hosts:
      - "test.chinapji.com:192.168.66.247"
  ngnix-server:
    image: nginx:1.13
    ports: 
      - "5000:5000"
    volumes: 
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on: 
      - chat-http_api_service
