version: "3"
services:
  face_recognition:
    image: shinoi2/pji-research:face_recognition
    volumes:
      - "/home/face_recognition/data:/data"

  light_detection:
    image: shinoi2/pji-research:light
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  lprnet_detection:
    image: shinoi2/pji-research:lprnet
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  plate_detection:
    image: shinoi2/pji-research:plate
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  vehicle_detection:
    image: shinoi2/pji-research:vehicle
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always
    entrypoint:
      - bash
      - -c
      - python3 -m paddle_serving_server.serve --model vehicle_server --port 9393 --gpu_id 0

  pedestrian_detection:
    image: shinoi2/pji-research:pedestrian
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always
    entrypoint:
      - bash
      - -c
      - python3 -m paddle_serving_server.serve --model pedestrian_server --port 9394 --gpu_id 0

  face_detection:
    image: shinoi2/pji-research:face
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always
    entrypoint:
      - bash
      - -c
      - python3 -m paddle_serving_server.serve --model face_server --port 9395 --gpu_id 0

  mask_detection:
    image: shinoi2/pji-research:mask
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always
    entrypoint:
      - bash
      - -c
      - python3 -m paddle_serving_server.serve --model mask_server --port 9396 --gpu_id 0
  
  http_api_service:
    image: shinoi2/pji-research:http_api_service
    environment:
      - GRPC_POLL_STRATEGY=poll
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always
    extra_hosts:
      - "test.chinapji.com:192.168.66.247"
  ngnix-server:
    image: nginx:1.13
    ports: 
      - "5000:5000"
    volumes: 
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on: 
      - chat-http_api_service-
