version: "3"
services:
  face_recognition:
    image: shinoi2/pji-research:face_recognition
    volumes:
      - "/home/face_recognition/data:/data"

  light_detection:
    image: shinoi2/pji-research:light
    restart: always
    volumes:
      - "/home/pji/workspace/light_Docker:/workspace"

  lprnet_detection_test:
    image: shinoi2/pji-research:lprnet
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - "/home/pji/workspace/LPRNet_Pytorch/app:/workspace"

  plate_detection_test:
    image: shinoi2/pji-research:plate
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - "/home/pji/workspace/Plate_Docker:/workspace"

  vehicle_detection:
    image: shinoi2/pji-research:paddleserving
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always
    volumes:
      - "/home/pji/workspace/ServingDocker/vehicle_server:/home/vehicle_server"
    entrypoint:
      - bash
      - -c
      - python3 -m paddle_serving_server.serve --model vehicle_server --port 9393 --gpu_id 0

  pedestrian_detection:
    image: shinoi2/pji-research:paddleserving
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always
    volumes:
      - "/home/pji/workspace/ServingDocker/pedestrian_server:/home/pedestrian_server"
    entrypoint:
      - bash
      - -c
      - python3 -m paddle_serving_server.serve --model pedestrian_server --port 9394 --gpu_id 0

  face_detection:
    image: shinoi2/pji-research:paddleserving
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always
    volumes:
      - "/home/pji/workspace/ServingDocker/face_server:/home/face_server"
    entrypoint:
      - bash
      - -c
      - python3 -m paddle_serving_server.serve --model vehicle_server --port 9395 --gpu_id 0

  mask_detection:
    image: shinoi2/pji-research:paddleserving
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always
    volumes:
      - "/home/pji/workspace/ServingDocker/mask_server:/home/mask_server"
    entrypoint:
      - bash
      - -c
      - python3 -m paddle_serving_server.serve --model mask_server --port 9396 --gpu_id 0
  
  http_api_service:
    image: shinoi2/pji-research:http_api_service
    environment:
      - GRPC_POLL_STRATEGY=poll
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always
    extra_hosts:
      - "test.chinapji.com:192.168.66.247"
  ngnix-server:
    image: nginx:1.13
    ports: 
      - "5000:5000"
    volumes: 
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on: 
      - chat-http_api_service