version: "3"
services:
  face_recognition:
    image: shinoi2/pji-research:face_recognition
    volumes:
      - "/home/face_recognition/data:/data"
  vehicle_detection:
    image: shinoi2/pji-research:paddleserving
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always
    volumes:
      - "/home/pji/research/app/vehicle_detector/vehicle_server:/home/vehicle_server"
    entrypoint:
      - bash
      - -c
      - python3 -m paddle_serving_server.serve --model vehicle_server --port 9393 --gpu_id 0
  http_api_service:
    image: shinoi2/pji-research:http_api_service
    environment:
      - GRPC_POLL_STRATEGY=poll
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always
    volumes:
      - "/home/pji/research/app/api:/root/api"
    extra_hosts:
      - "test.chinapji.com:192.168.66.247"
  ngnix-server:
    image: nginx:1.13
    ports: 
      - "5000:5000"
    volumes: 
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on: 
      - chat-http_api_service
