version: "3"
services:
  face_recognition:
    image: registry.cn-hangzhou.aliyuncs.com/chinapji/research_face_recognition:20220622
    volumes:
      - "./face_recognition_data:/data"
    environment:
      - APP_ID=CAv7zJJJHGxninFhZfq4uKuZL2uV2UYiFA1bcoKfV3yi
      - SDK_KEY=3JK6qHZFpLdzzd1xNpjVJugPK2UuYywxBAMkMUTa2FAZ

  # face_recognition:
  #   image: registry.cn-hangzhou.aliyuncs.com/chinapji/research_face_recognition:20220526
  #   volumes:
  #     - "./face_recognition_data_pre:/data"
  #   environment:
  #     - APP_ID=CAv7zJJJHGxninFhZfq4uKuZL2uV2UYiFA1bcoKfV3yi
  #     - SDK_KEY=3JK6qHZFpLdzzd1xNpjVJugPK2UuYywxBAMkMUTa2FAZ

  light_detection:
    image: registry.cn-hangzhou.aliyuncs.com/chinapji/research_light:20220526
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  object_detection:
    image: registry.cn-hangzhou.aliyuncs.com/chinapji/research_object:20220601
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  plate_detection:
    image: registry.cn-hangzhou.aliyuncs.com/chinapji/research_plate:20220526

  vehicle_detection:
    image: registry.cn-hangzhou.aliyuncs.com/chinapji/research_vehicle:20220526
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always
    entrypoint:
      - bash
      - -c
      - python3 -m paddle_serving_server.serve --model vehicle_server --port 9393 --gpu_id 0  --thread 16

  pedestrian_detection:
    image: registry.cn-hangzhou.aliyuncs.com/chinapji/research_pedestrian:20220526
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always
    entrypoint:
      - bash
      - -c
      - python3 -m paddle_serving_server.serve --model pedestrian_server --port 9394 --gpu_id 0  --thread 32

  mask_detection:
    image: registry.cn-hangzhou.aliyuncs.com/chinapji/research_mask:20220526
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always
    entrypoint:
      - bash
      - -c
      - python3 -m paddle_serving_server.serve --model mask_server --port 9396 --gpu_id 0 --thread 32

  speech_server:
    image: registry.cn-hangzhou.aliyuncs.com/chinapji/research_speech
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always

  http_api_service:
    image: registry.cn-hangzhou.aliyuncs.com/chinapji/research_http_api_service:20220613
    environment:
      - GRPC_POLL_STRATEGY=poll
    volumes:
      - "./app/asr/__init__.py:/root/asr/__init__.py"
      - "./app/api/v2/asr.py:/root/api/v2/asr.py"
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - face_recognition
      - light_detection
      - object_detection
      - vehicle_detection
      - plate_detection 
      - pedestrian_detection
      - mask_detection
      - speech_server
    extra_hosts:
      - "test.chinapji.com:192.168.66.247" 
  # http_api_service_pre:
  #   image: registry.cn-hangzhou.aliyuncs.com/chinapji/research_http_api_service:20220613
  #   environment:
  #     - GRPC_POLL_STRATEGY=poll
  #     - PRE=1
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities: [gpu]
  #   restart: always
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - face_recognition_pre
  #     - light_detection
  #     - object_detection
  #     - vehicle_detection
  #     - plate_detection 
  #     - pedestrian_detection
  #     - mask_detection
  #     - speech_server
