name: docker-build

on:
  watch:
    types: [started]

jobs:
  docker:
    runs-on: ubuntu-18.04
    if: github.actor == github.event.repository.owner.login

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
      -
        name: Download model file
        run: wget https://github.com/shinoi2/research/releases/download/docker-build-20220321/paddle.tar.gz &&
             wget https://github.com/shinoi2/research/releases/download/docker-build-20220321/light.pth
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pji-research:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pji-research:http_api_service
          cache-to: type=inline
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.ACCESS_TOKEN }}
